import Foundation

/// One SF Symbol offered in the template icon picker.
public struct SymbolEntry: Hashable, Sendable {
    public let name: String
    /// Search terms from the system SF Symbols catalog.
    public let keywords: [String]

    public init(name: String, keywords: [String] = []) {
        self.name = name
        self.keywords = keywords
    }
}

/// A group of symbols in the icon picker.
public struct SymbolCategory: Identifiable, Hashable, Sendable {
    public let id: String
    public let title: String
    public let symbols: [SymbolEntry]

    public init(id: String, title: String, symbols: [SymbolEntry]) {
        self.id = id
        self.title = title
        self.symbols = symbols
    }
}

/// The SF Symbols a template can use as its icon.
///
/// The catalog is generated by `scripts/generate-symbol-catalog.py`, which
/// validates every name against the SF Symbols catalog installed with macOS,
/// so only symbols that exist on the deployment target are offered.
public enum SymbolCatalog {
    public static var categories: [SymbolCategory] { generatedCategories }

    /// Every symbol name, in catalog order, without duplicates.
    public static let allNames: [String] = {
        var seen = Set<String>()
        return generatedCategories.flatMap(\.symbols).map(\.name).filter { seen.insert($0).inserted }
    }()

    private static let nameSet = Set(allNames)

    public static func contains(_ name: String) -> Bool {
        nameSet.contains(name)
    }

    /// Symbols matching a query, optionally within one category. Matches the
    /// symbol name's words (`chevron.left.forwardslash` → "forwardslash"),
    /// system keywords, and category titles. An empty query returns everything.
    public static func search(_ query: String, categoryID: String? = nil) -> [String] {
        let scope = categoryID.map { id in generatedCategories.filter { $0.id == id } } ?? generatedCategories
        let terms = query.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
        var seen = Set<String>()
        var results: [String] = []
        for category in scope {
            for entry in category.symbols where !seen.contains(entry.name) {
                let haystack = [entry.name, category.title.lowercased()] + entry.keywords
                let matches = terms.allSatisfy { term in haystack.contains { $0.contains(term) } }
                if matches {
                    seen.insert(entry.name)
                    results.append(entry.name)
                }
            }
        }
        return results
    }
}

/// Template icon rules: SF Symbol names only, with migration of the emoji
/// icons stored by Calendar Time Logger 1.0.
public enum TemplateSymbol {
    /// Icon for new templates.
    public static let defaultName = "briefcase"
    /// Used when a stored icon can't be mapped to a symbol.
    public static let fallbackName = "square.grid.2x2"

    /// Emoji used by 1.0 (defaults and editor suggestions) and other common
    /// choices, mapped to the closest symbol. Keys have no variation selector.
    public static let legacyEmojiMap: [String: String] = [
        // 1.0 defaults and suggestions
        "💻": "laptopcomputer", "📚": "book", "🧪": "flask", "✍": "pencil", "🎨": "paintpalette",
        "📊": "chart.bar", "🧠": "brain.head.profile", "📝": "square.and.pencil", "🎧": "headphones",
        "🏋": "dumbbell", "📞": "phone", "🛠": "wrench.and.screwdriver", "🔬": "magnifyingglass",
        "📈": "chart.line.uptrend.xyaxis", "🎓": "graduationcap", "💼": "briefcase", "🗂": "folder",
        "🧾": "receipt", "🎬": "film", "🌱": "leaf",
        // Other common icons
        "📖": "book", "📕": "book.closed", "📗": "book.closed", "📘": "book.closed", "📙": "book.closed",
        "🖥": "desktopcomputer", "⌨": "keyboard", "🐞": "ladybug", "🐛": "ladybug", "📁": "folder",
        "📂": "folder", "📄": "doc.text", "📃": "doc.text", "📧": "envelope", "✉": "envelope",
        "📨": "envelope", "💬": "message", "📷": "camera", "📸": "camera", "🎵": "music.note",
        "🎶": "music.note.list", "🎮": "gamecontroller", "💰": "banknote", "💵": "banknote",
        "💳": "creditcard", "❤": "heart", "🏃": "figure.run", "🧘": "figure.yoga", "✈": "airplane",
        "🚗": "car", "🏠": "house", "🔧": "wrench.adjustable", "🔨": "hammer", "⚙": "gearshape",
        "🔒": "lock", "👤": "person", "👥": "person.2", "💡": "lightbulb", "🎁": "gift",
        "☕": "cup.and.saucer", "🌳": "tree", "☀": "sun.max", "🌙": "moon", "⭐": "star",
        "🏆": "trophy", "🎯": "target", "⏰": "alarm", "⏱": "stopwatch", "📅": "calendar",
        "🗓": "calendar", "✅": "checkmark.circle", "📋": "list.bullet.clipboard", "🔍": "magnifyingglass",
        "🔎": "magnifyingglass", "🌍": "globe.europe.africa", "🗺": "map", "✏": "pencil",
        "🖌": "paintbrush", "🖊": "pencil", "📐": "pencil.and.ruler", "📏": "ruler", "🧮": "function",
        "🔭": "binoculars", "⚛": "atom", "🚀": "paperplane", "🏢": "building.2", "🛒": "cart",
    ]

    /// Whether a stored value already looks like an SF Symbol name
    /// (lowercase ASCII words separated by dots).
    public static func looksLikeSymbolName(_ value: String) -> Bool {
        guard let first = value.unicodeScalars.first, CharacterSet.lowercaseLetters.contains(first) || CharacterSet.decimalDigits.contains(first) else {
            return false
        }
        let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyz0123456789.")
        return value.unicodeScalars.allSatisfy { allowed.contains($0) } && !value.hasSuffix(".") && !value.contains("..")
    }

    /// The symbol a stored icon value should display. Never returns emoji:
    /// symbol names pass through, known emoji are mapped, anything else
    /// becomes the fallback symbol. Empty input returns an empty string.
    public static func normalizedName(_ stored: String) -> String {
        let trimmed = stored.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return "" }
        if looksLikeSymbolName(trimmed) { return trimmed }
        if let mapped = mappedEmoji(trimmed) { return mapped }
        return fallbackName
    }

    /// Like `normalizedName`, but also replaces symbol names that aren't in
    /// the catalog, so the result always renders.
    public static func displayName(_ stored: String) -> String {
        let name = normalizedName(stored)
        return SymbolCatalog.contains(name) ? name : fallbackName
    }

    /// Whether a stored icon needs migrating to a symbol name.
    public static func needsMigration(_ stored: String) -> Bool {
        let trimmed = stored.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.isEmpty && !looksLikeSymbolName(trimmed)
    }

    private static func mappedEmoji(_ value: String) -> String? {
        // Compare without variation selectors (U+FE0E/U+FE0F) and skin tones,
        // and try the first character alone (1.0 stored a single character).
        func strip(_ text: String) -> String {
            String(String.UnicodeScalarView(text.unicodeScalars.filter {
                $0.value != 0xFE0F && $0.value != 0xFE0E && !(0x1F3FB...0x1F3FF).contains($0.value)
            }))
        }
        let candidates = [strip(value), value.first.map { strip(String($0)) } ?? ""]
        for candidate in candidates where !candidate.isEmpty {
            if let mapped = legacyEmojiMap[candidate] { return mapped }
        }
        return nil
    }
}
